language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qtbase5-dev libmagick++-dev qt5-qmake tree yasm
  
script:
  - export CWD=`pwd`
  - mkdir $CWD/build1
  - cd $CWD/build1
  - qmake -qt=qt5 CONFIG+=no_ffmpeg CONFIG+=release CONFIG+=legacy_magick CONFIG+=v7 PREFIX=/usr  ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build2
  - cd $CWD/build2
  - qmake -qt=qt5 CONFIG+=no_ffmpeg CONFIG+=debug CONFIG+=legacy_magick CONFIG+=v7 PREFIX=/usr  ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
