language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qtbase5-dev libmagick++-dev qt5-qmake tree
  
script:
  - export CWD=`pwd`
  - mkdir $CWD/build1
  - cd $CWD/build1
  - qmake -qt=qt5 CONFIG+=release CONFIG+=legacy_magick PREFIX=/usr  ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build3
  - cd $CWD/build3
  - qmake -qt=qt5 CONFIG+=debug CONFIG+=legacy_magick PREFIX=/usr  ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build5
  - cd $CWD/build5
  - qmake -qt=qt5 CONFIG+=debug CONFIG+=legacy_magick PREFIX=/usr CONFIG+=basic CONFIG+=no_desktop ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - mkdir $CWD/build7
  - cd $CWD/build7
  - qmake -qt=qt5 CONFIG+=release CONFIG+=legacy_magick PREFIX=/usr CONFIG+=basic CONFIG+=no_desktop ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
