theme: jekyll-theme-slate
title: QtFM
show_downloads: true
github:
  zip_url: https://github.com/rodlie/qtfm/archive/6.1.0-beta1.zip
  tar_url: https://github.com/rodlie/qtfm/archive/6.1.0-beta1.tar.gz
